# 監控模組
monitor:
  data: "./data"
  days: 3 # 天
  cpu: 
    enable: true
    interval: 10 # 秒
  memory: 
    enable: true
    interval: 10 # 秒
  disk: 
    enable: true
    interval: 10 # 秒
  net: 
    enable: true
    interval: 10 # 秒

# 網路模組
network:
  data: "./data/offset.json"
  category: ["cpu", "disk", "memory", "network"]
  host: "127.0.0.1:50051"
  ignore_older: 3 # 天

# Log 設定
log:
  debug: true
  path: "./logs"     # 日誌儲存目錄
  max_size: 10       # 單一 log 檔最大大小（MB）
  max_age: 7         # 保留天數
  max_backups: 5     # 最多保留幾個舊檔案
